### PR TITLE
[AAP-4602] - Updated config, layout,  logo, masthead, top toolbar

### PR DESCRIPTION
**Pull request by lgalis**
First round of changes - include the following tasks from AAP-4602

1. Move project configuration to a separate folder ( config )
2. Updated packages, audit
3. Updated logo
4. Adds the user menu to the masthead with login/logout (first implementation)
5. Adds top toolbar to all components 

More items in AAP-4602 will be in follow up PRs

Screenshot from 2022-07-12 13-29-39
Screenshot from 2022-07-12 13-30-00
Screenshot from 2022-07-12 13-30-28
Screenshot from 2022-07-12 13-38-17

### CODE REVIEW

**Comment by eclarizio** [comment]
@lgalis It doesn't look like this actually linked to the JIRA issue, I'm not sure if it's because the title has to be `[AAP-4602]` and it didn't match, or if maybe something is configured incorrectly with the AAP project. Can you try updating the title and closing/reopening to see if that automatically links JIRA to github for this PR?

**Comment by lgalis** [comment]
@eclarizio - this PR does not include all the code changes required for AAP-4602, this is why I added the partial there - I will add a link to this PR in Jira and and will mark the title of the PR with the final changes with [AAP-4602]

**Comment by lgalis** [comment]
@eclarizio - I updated the title, closed/reopened

**Comment by lgalis** [comment]
@benthomasson - I missed adding that file to git - that's fixed now, thank you. I'll be adding tests and a github action to run them in a follow up PR

**Review by benthomasson — APPROVED** [review]

**Pull request closed without merging**
