### PR TITLE
[UI][AAP-7623] Rename audit to action

### PR DESCRIPTION
**Pull request by lgalis**
**To be merged after #276**

Rename audit to action per the new UX mocks. Add action_type to the Recent actions list and the action details tab.

Screenshot from 2022-12-08 17-29-38

Screenshot from 2022-12-08 16-27-14

Screenshot from 2022-12-09 14-11-37

### CODE REVIEW

**Comment by Dostonbek1** [comment]
@lgalis Does this have backend piece too yet?

**Comment by lgalis** [comment]
@Dostonbek1 - this PR is using the old /audit endpoints ( the 'type' will not be there , so there will be nothing in the UI for it)
There is a Jira card to update the endpoints - once the endpoints are renamed, the UI will have to be updated with the new endpoints. https://issues.redhat.com/browse/AAP-7630

**Review by ddonahue007 — APPROVED** [review]
lgtm

**Review by Dostonbek1 — APPROVED** [review]
lgtm

**Pull request closed without merging**
