### PR TITLE
fix postgres startup for docker compose

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**
Add a healthcheck for postgres to avoid connection errors when the stack starts.

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
@cutwater

**Comment by cutwater** [comment]
@Alex-Izquierdo AFAIK healthcheck has no effect on service startup in `docker-compose`. The `app` container itself must check explicitly for database readiness.

https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on

> There are several things to be aware of when using depends_on:

>    depends_on does not wait for db and redis to be “ready” before starting web - only until they have been started. If you need to wait for a service to be ready, see [Controlling startup order](https://docs.docker.com/compose/startup-order/) for more on this problem and strategies for solving it.

**Comment by Alex-Izquierdo** [comment]
@cutwater I'm not sure, maybe the documentation is outdated. Or Maybe the [default condition ](https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1) is "service healthy". The last version from pip seems honors the healthcheck. You can check it. I did several tests and it works.

**Comment by cutwater** [comment]
@Alex-Izquierdo I tested in with `docker-compose` v2.6.1 and it still fails, but looks like I was looking at the outdated specification indeed. With your changes and additionally updating `depends_on` as the following, it works as expected:

```
    depends_on:
      postgres:
        condition: service_healthy
```

**Comment by Alex-Izquierdo** [comment]
@cutwater Ok. I added the condition and update the docs to recommend the latest version of docker-compose

**Review by cutwater — APPROVED** [review]

**Pull request merged**
