### PR TITLE
point ansible-event requirement to the latest version of the main branch

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**
At this stage of development I think it's better to point the ansible-events to the latest version of the main branch.

### CODE REVIEW

**Review by cutwater — APPROVED** [review]

**Review by cutwater — CHANGES_REQUESTED** [review]
@Alex-Izquierdo Can you please describe use case of this?

**Review by benthomasson — COMMENTED** [review]
I do this when I build containers, but I am not sure it should be package requirements.

**Comment by cutwater** [comment]
@benthomasson I'm rather tentative on this change. It might be useful to simplify dev environment setup and since we don't have a formal release at the moment it's probably won't hurt, but in general I'd prefer to avoid specifying it in the dependencies list and make the decision per specific environment.

**Comment by benthomasson** [comment]
I am not sure how it would work in dev environments.  I usually have both repos checked out and use  `pip install -e .` in the same venv.    I guess that would override the package requirements.

**Comment by Alex-Izquierdo** [comment]
@cutwater 
Indeed, it is to facilitate development (and also testing). 
@benthomasson I think your workaround will work as long as you run the `pip install` in `ansible-events-ui` first. 

Anyway, I think this affects more to you than me, so if you prefer don't it, I close the ticket. 

Would you agree to enable it by default (at least temporally) in the docker-compose?

**Comment by benthomasson** [comment]
Yeah use it in the docker-compose setup for now.

**Pull request closed without merging**
