### PR TITLE
Fix test cloning and processing actual repository

### PR DESCRIPTION
**Pull request by cutwater**
The `test_create_project` during execution was cloning actual
repository from GitHub.
Unit and integration tests must not depend on extenal resources.

This change patches actual calls to `clone_project` and `sync_project`
functions and replaces them with mocks.

### CODE REVIEW

**Comment by cutwater** [comment]
@shannon-donahue @benthomasson please review

**Review by shannon-donahue — APPROVED** [review]
LGTM

**Comment by benthomasson** [comment]
Do we have any end-to-end or system tests yet?   @cutwater @Alex-Izquierdo @ttuffin

**Comment by Alex-Izquierdo** [comment]
@benthomasson yes, here: https://github.com/Alex-Izquierdo/ansible-events-qa/blob/main/ansible_events_qa/tests/api/projects/test_projects.py#L25

**Pull request merged**
