### PR TITLE
Updated projects list page

### PR DESCRIPTION
**Pull request by lgalis**
- Added a new table with toolbar component, I18N enabled
- Use the new component in the project list page 
- WIP - adding type interfaces for ts - to complete in a follow up PR.
( Delete will be implemented in a follow up PR. Search and pagination will be implemented when backend allows )

Screenshot from 2022-07-15 19-41-10
Screenshot from 2022-07-15 19-37-28

### CODE REVIEW

**Comment by benthomasson** [comment]
I get this error when trying `npm run build`

```
ERROR in ./node_modules/@redhat-cloud-services/frontend-components/esm/BulkSelect/BulkSelect.js 37:0-36
Module not found: Error: Can't resolve 'classnames' in '/Users/ben/git/ansible-events-ui/ui/node_modules/@redhat-cloud-services/frontend-components/esm/BulkSelect'
```

**Comment by lgalis** [comment]
@benthomasson - I updated the package-lock on the branch. Please let me know of you still have issues with the updated package versions

**Comment by benthomasson** [comment]
@lgalis I removed node_modules and ran `npm ci` and `npm run build` and I still get 

```ERROR in ./node_modules/@redhat-cloud-services/frontend-components/esm/BulkSelect/BulkSelect.js 37:0-36
Module not found: Error: Can't resolve 'classnames' in '/Users/ben/git/ansible-events-ui/ui/node_modules/@redhat-cloud-services/frontend-components/esm/BulkSelect'```

**Review by benthomasson — APPROVED** [review]

**Comment by benthomasson** [comment]
Upgrading to node 16 fixed my issue above.

**Pull request merged**
